apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: litecoin
  name: litecoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litecoin
  serviceName: litecoin
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      containers:
      - image: wstewart90/litecoin:0.18.1
        name: litecoin
        ports:
        - containerPort: 9333
          name: litecoind
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /home/litecoin
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
